from dataclasses import dataclass

from playwright.sync_api import Page, Locator

from locators.base_page.base_page_locators import BasePageLocators
from pages.base_page.base_page import BasePage


@dataclass
class RentFlatForDayLocators(BasePageLocators):
    """Локаторы для страницы - 'Подать объявление аренда квартиры на сутки'"""

    page: Page
    wait_timeout = 5000
    common_delay = 1000

    # def location_dropdown(self, name: str) -> Locator:
    #     # {name} подставится в строку при вызове метода
    #     return self.page.get_by_role(role="button", name=name)

    def __init__(self, page: Page):
        super().__init__(page)
        self.page = page
        self.url = "https://realt.by/podat-obyavlenie/"
        self.add_adv_button = page.get_by_role(role="button", name="Добавить объявление")
        self.rent_flat_for_day_button = page.get_by_role(role="button", name="Сдать посуточно")
        self.residential_button = page.get_by_role(role="button", name="Жилая")
        self.flat_button = page.get_by_role(role="button", name="Квартира")

        self.rooms = page.get_by_text(text="5", exact=True)


"""
import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://dev2.realt.by/")
    page.get_by_role("button", name="Принять").click()
    page.get_by_role("link", name="Войти").click()
    page.get_by_role("textbox", name="Email / логин / +").click()
    page.get_by_role("textbox", name="Email / логин / +").fill("dev_user_01_lord@rover.info")
    page.get_by_role("button", name="Продолжить").click()
    page.get_by_role("textbox", name="Введите пароль").fill("Oracle01")
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("button", name="Добавить объявление").click()
    page.get_by_role("button", name="Сдать посуточно").click()
    page.get_by_role("button", name="Жилая").click()
    page.get_by_role("button", name="Квартира").click()
    page.get_by_role("button", name="Понятно").click()
    page.get_by_text("Квартира", exact=True).click()
    page.get_by_role("textbox", name="Адрес").click()
    page.get_by_role("textbox", name="Адрес").fill("минск")
    page.get_by_role("button", name="г. Минск Минский р-н, Минская область").click()
    page.get_by_role("textbox", name="Улица").click()
    page.get_by_role("textbox", name="Улица").fill("берута")
    page.get_by_role("button", name="Берута ул").click()
    page.get_by_role("textbox", name="Дом", exact=True).click()
    page.get_by_role("textbox", name="Дом", exact=True).fill("11")
    page.get_by_role("textbox", name="Корпус").click()
    page.get_by_role("textbox", name="Корпус").fill("а")
    page.get_by_text("5", exact=True).click()
    page.get_by_text("Кухня-столовая").click()
    page.get_by_text("Евроремонт").click()
    page.get_by_role("textbox", name="Площадь общая, м²").click()
    page.get_by_role("textbox", name="Площадь общая, м²").fill("140")
    page.get_by_role("textbox", name="Площадь жилая, м²").click()
    page.get_by_role("textbox", name="Площадь жилая, м²").fill("80")
    page.get_by_role("textbox", name="Площадь кухни, м²").click()
    page.get_by_role("textbox", name="Площадь кухни, м²").fill("25")
    page.get_by_role("textbox", name="Этаж", exact=True).click()
    page.get_by_role("textbox", name="Этаж", exact=True).fill("9")
    page.get_by_role("textbox", name="Этажей в доме").click()
    page.get_by_role("textbox", name="Этажей в доме").fill("16")
    page.get_by_role("textbox", name="Год постройки").click()
    page.get_by_role("textbox", name="Год постройки").fill("2010")
    page.get_by_text("3 спальни").click()
    page.get_by_role("textbox", name="Максимум гостей").click()
    page.get_by_role("textbox", name="Максимум гостей").fill("4")
    page.get_by_role("button", name="Основные спальные места").click()
    page.get_by_role("textbox", name="Основное спальное место").nth(1).click()
    page.get_by_role("textbox", name="Основное спальное место").nth(1).click()
    page.locator("[id=\"capacity.mainPlaces[0].quantity\"]").click()
    page.locator("[id=\"capacity.mainPlaces[0].quantity\"]").click()
    page.locator("[id=\"capacity.mainPlaces[0].quantity\"]").click()
    page.locator("[id=\"capacity.mainPlaces[0].quantity\"]").fill("2")
    page.get_by_role("textbox", name="Количество ванных комнат с туалетом").click()
    page.get_by_role("textbox", name="Количество ванных комнат с туалетом").fill("2")
    page.get_by_role("textbox", name="Количество отдельных туалетов").click()
    page.get_by_role("textbox", name="Количество отдельных туалетов").fill("2")
    page.get_by_role("textbox", name="Количество ванных комнат без туалета").click()
    page.get_by_role("textbox", name="Количество ванных комнат без туалета").fill("0")
    page.get_by_role("switch", name="Можно с детьми").click()
    page.get_by_role("switch", name="Младенцы до 2х лет").click()
    page.get_by_role("switch", name="Дети 2-12 лет").click()
    page.get_by_role("switch", name="Подростки 13-17 лет").click()
    page.get_by_role("switch", name="Можно с питомцами").click()
    page.get_by_role("switch", name="Курение разрешено").click()
    page.locator("div").filter(has_text=re.compile(r"^Курение разрешено$")).first.click()
    page.get_by_role("switch", name="Предоставляются отчетные документы").click()
    page.get_by_role("textbox", name="Парковка").click()
    page.get_by_role("button", name="Есть платная парковка").click()
    page.get_by_role("textbox", name="Парковка").click()
    page.get_by_role("textbox", name="Парковка").click()
    page.locator("div").filter(has_text="Подать объявлениеТип объявленияКвартира (Realt.Бронь)BETAИзменить1").nth(3).click()
    page.get_by_role("switch", name="Парковка охраняется").click()
    page.get_by_role("textbox", name="Парковка").click()
    page.get_by_role("button", name="Есть бесплатная парковка").click()
    page.get_by_text("Балкон").click()
    page.get_by_text("Wi-Fi").first.click()
    page.get_by_text("Кондиционер").first.click()
    page.get_by_text("Пандус").first.click()
    page.get_by_text("Полотенца").first.click()
    page.get_by_text("Постельное бельё").first.click()
    page.get_by_text("Электрочайник").first.click()
    page.get_by_text("Фен").first.click()
    page.get_by_text("Фен").first.click()
    page.get_by_text("Микроволновка").first.click()
    page.get_by_text("Телевизор").first.click()
    page.get_by_text("Фен").first.click()
    page.get_by_text("На город").click()
    page.get_by_text("На реку").click()
    page.get_by_text("На озеро").click()
    page.get_by_text("На лес").click()
    page.get_by_text("На парк").click()
    page.get_by_text("На улицу").click()
    page.get_by_text("Во двор").click()
    page.get_by_text("На бассейн").click()
    page.get_by_text("На достопримечательность").click()
    page.get_by_text("На сад").click()
    page.get_by_text("Биде").click()
    page.locator("div").filter(has_text=re.compile(r"^Ванна$")).first.click()
    page.get_by_text("Гигиенический душ").click()
    page.get_by_text("Дополнительная ванная").click()
    page.get_by_text("Дополнительный туалет").click()
    page.get_by_text("Душ", exact=True).click()
    page.get_by_text("Общая ванная комната").click()
    page.get_by_text("Общий туалет").click()
    page.get_by_text("Сауна").click()
    page.get_by_text("Тапочки").click()
    page.get_by_text("Туалетные принадлежности").click()
    page.get_by_text("Халат").click()
    page.get_by_text("Общий душ / душевая").click()
    page.get_by_text("Барная стойка").click()
    page.get_by_text("Блендер").click()
    page.get_by_text("Блендер").click()
    page.get_by_text("Блендер").click()
    page.get_by_text("Блендер").click()
    page.get_by_text("Блендер").click()
    page.get_by_text("Газовая плита").click()
    page.get_by_text("Духовка").click()
    page.get_by_text("Кофеварка").click()
    page.get_by_text("Кофемашина").click()
    page.get_by_text("Кухонный гарнитур").click()
    page.get_by_text("Мини-бар").click()
    page.get_by_text("Морозильник").click()
    page.get_by_text("Мультиварка").click()
    page.get_by_text("Обеденный стол").click()
    page.get_by_text("Обеденный стол").click()
    page.get_by_text("Посудомоечная машина").click()
    page.get_by_text("Обеденный стол").click()
    page.get_by_text("Посуда и принадлежности").click()
    page.get_by_text("Столовые приборы").click()
    page.get_by_text("Тостер").click()
    page.get_by_text("Турка для приготовления кофе").click()
    page.get_by_text("Фильтр для воды").click()
    page.get_by_text("Холодильник").click()
    page.get_by_text("Электроплита").click()
    page.get_by_text("Бассейн", exact=True).click()
    page.get_by_text("Вентилятор").click()
    page.get_by_text("Вешалка для одежды").click()
    page.get_by_text("Водонагреватель", exact=True).click()
    page.get_by_text("Газовый водонагреватель").click()
    page.get_by_text("Гардеробная").click()
    page.get_by_text("Гостиный уголок").click()
    page.get_by_text("Деревянный / паркетный пол").click()
    page.get_by_text("Джакузи (гидромассажная ванна)").click()
    page.get_by_text("Домофон").click()
    page.get_by_text("Журнальный столик").click()
    page.get_by_text("Журнальный столик").click()
    page.get_by_text("Камин").click()
    page.get_by_text("Звукоизоляция").click()
    page.get_by_text("Звукоизоляция").click()
    page.get_by_text("Журнальный столик").click()
    page.get_by_text("Звукоизоляция").click()
    page.get_by_text("Ковровое покрытие").click()
    page.get_by_text("Ламинат").click()
    page.get_by_text("Линолеум").click()
    page.get_by_text("Место для хранения лыж / сноуборда").click()
    page.get_by_text("Металлическая дверь").click()
    page.get_by_text("Москитная сетка").click()
    page.get_by_text("Новогодняя ёлка").click()
    page.get_by_text("Обогреватель").click()
    page.get_by_text("Одеяла с электроподогревом").click()
    page.get_by_text("Персональный компьютер").click()
    page.get_by_text("Плиточный / мраморный пол").click()
    page.get_by_text("Пляжные полотенца").click()
    page.get_by_text("Проводной интернет").click()
    page.get_by_text("Пылесос").click()
    page.get_by_text("Рабочий стол").click()
    page.get_by_text("Раскладная кровать").click()
    page.get_by_text("Сейф").click()
    page.get_by_text("Стиральная машина").click()
    page.get_by_text("Сушилка для белья").click()
    page.get_by_text("Сушильная машина").click()
    page.locator("#facilities").get_by_text("Телефон").click()
    page.get_by_text("Утюг с гладильной доской").click()
    page.get_by_text("Центральное отопление").click()
    page.get_by_text("Чистящие средства").click()
    page.get_by_text("Шкаф").click()
    page.get_by_text("Шторы блэкаут").click()
    page.get_by_text("Smart TV").click()
    page.get_by_text("Бильярд", exact=True).click()
    page.get_by_text("Игровая консоль").click()
    page.get_by_text("Кабельное ТВ").click()
    page.get_by_text("Книги").click()
    page.get_by_text("Музыкальный центр").click()
    page.get_by_text("Настольные игры").click()
    page.get_by_text("Настольный теннис").click()
    page.get_by_text("Ноутбук").click()
    page.get_by_text("Платные ТВ-каналы").click()
    page.get_by_text("Радио").click()
    page.get_by_text("Спутниковое ТВ").click()
    page.get_by_text("Эфирное ТВ").click()
    page.get_by_text("Банный чан").click()
    page.get_by_text("Баня (на территории)").click()
    page.get_by_text("Барбекю / мангал").click()
    page.get_by_text("Бассейн с подогревом").click()
    page.get_by_text("Беседка").click()
    page.get_by_text("Веранда").click()
    page.get_by_text("Гамак").click()
    page.get_by_text("Гараж", exact=True).click()
    page.get_by_text("Детские качели").click()
    page.get_by_text("Детские качели").click()
    page.get_by_text("Детские качели").click()
    page.get_by_text("Детские качели").click()
    page.get_by_text("Детские качели").click()
    page.get_by_text("Игровая площадка").click()
    page.get_by_text("Лодка").click()
    page.get_by_text("Мебель на улице").click()
    page.get_by_text("Обеденная зона на улице").click()
    page.get_by_text("Открытый бассейн").click()
    page.get_by_text("Охраняемая территория").click()
    page.get_by_text("Патио").click()
    page.get_by_text("Пляжный зонтик").click()
    page.get_by_text("Принадлежность для барбекю").click()
    page.get_by_text("Садовая мебель").click()
    page.get_by_text("Спортивный зал").click()
    page.get_by_text("Спортивный зал").click()
    page.get_by_text("Футбольное поле").click()
    page.get_by_text("Шезлонги").click()
    page.get_by_text("Спортивный зал").click()
    page.get_by_text("Терраса").click()
    page.get_by_text("SPA-центр").click()
    page.get_by_text("Альпинизм").click()
    page.get_by_text("Баня (за территорией)").click()
    page.get_by_text("Бильярдный клуб").click()
    page.get_by_text("Боулинг").click()
    page.get_by_text("Верховая езда").click()
    page.get_by_text("Водные виды спорта").click()
    page.get_by_text("Гольф").click()
    page.get_by_text("Горные лыжи").click()
    page.get_by_text("Езда на снегоходах").click()
    page.get_by_text("Жильё находится в частом секторе").click()
    page.get_by_text("Зоопарк").click()
    page.get_by_text("Каток").click()
    page.get_by_text("Кинотеатр").click()
    page.get_by_text("Лес", exact=True).click()
    page.get_by_text("Ночной клуб").click()
    page.get_by_text("Парк аттракционов").click()
    page.get_by_text("Прокат велосипедов").click()
    page.get_by_text("Прокат роликовых коньков").click()
    page.get_by_text("Пруд / озеро поблизости").click()
    page.get_by_text("Рыбалка").click()
    page.get_by_text("Театр", exact=True).click()
    page.get_by_text("Теннисный клуб").click()
    page.get_by_text("Яхт-клуб").click()
    page.get_by_text("Охота").click()
    page.get_by_text("Высокий стул для ребенка").click()
    page.get_by_text("Детская кроватка").click()
    page.get_by_text("Детский горшок").click()
    page.get_by_text("Защита на окнах").click()
    page.get_by_text("Защитные крышки на розетках").click()
    page.get_by_text("Игры / игрушки для детей").click()
    page.get_by_text("Кровать-манеж").click()
    page.get_by_text("Пеленальный стол").click()
    page.get_by_text("Стульчик для кормления").click()
    page.get_by_text("Возможно бесконтактное заселение").click()
    page.get_by_text("Доступ для инвалидов").click()
    page.get_by_text("Лифт").click()
    page.get_by_text("Находится на первом этаже").click()
    page.get_by_text("Туалет с поручнями").click()
    page.get_by_role("button", name="Выберите фотографии").click()
    page.get_by_role("button", name="Выберите фотографии").set_input_files(["Beruta_11_a_003.jpg", "Beruta_11_a_004.jpg", "Beruta_11_a_005.jpg", "house.jpg"])
    page.get_by_role("textbox", name="Ссылка на видео YouTube").click()
    page.get_by_role("textbox", name="Ссылка на видео YouTube").fill("www.youtube.com")
    page.get_by_role("textbox", name="3D тур").click()
    page.get_by_role("textbox", name="3D тур").fill("www.3dtur.com")
    page.get_by_role("textbox", name="Заголовок").click()
    page.get_by_role("textbox", name="Заголовок").fill("это описание заголовок")
    page.get_by_role("textbox", name="Краткое описание").click()
    page.get_by_role("textbox", name="Краткое описание").fill("это краткое описание данного объекта при подаче объявления")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.locator("html").click()
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").fill("это подробное описание данного объекта при подаче объявления !")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("Shift+Home")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ControlOrMeta+с")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.locator("html").click()
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_text("это подробное описание данного объекта при подаче объявления !").click()
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ArrowRight")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ControlOrMeta+м")
    page.locator("iframe[title=\"Rich Text Area\"]").content_frame.get_by_label("Rich Text Area. Press ALT-0").press("ControlOrMeta+м")
    page.get_by_text("Физическое лицо").click()
    page.get_by_role("textbox", name="Фамилия").click()
    page.get_by_role("textbox", name="Фамилия").fill("сорокин")
    page.get_by_role("textbox", name="Фамилия").press("Tab")
    page.get_by_role("textbox", name="Имя", exact=True).click()
    page.get_by_role("textbox", name="Имя", exact=True).fill("алексей")
    page.get_by_role("textbox", name="Отчество (при наличии)").click()
    page.get_by_role("textbox", name="Отчество (при наличии)").fill("михайлович")
    page.get_by_role("textbox", name="УНП").click()
    page.get_by_role("textbox", name="УНП").fill("1234567890")
    page.get_by_role("button", name="Показать список").click()
    page.get_by_role("button", name="Очистить").click()
    page.get_by_role("textbox", name="Телефон").click()
    page.get_by_role("textbox", name="Телефон").fill("+375(29)664-53-11_")
    page.get_by_role("textbox", name="Имя (контактное)").click()
    page.get_by_role("textbox", name="Имя (контактное)").press("ArrowRight")
    page.get_by_role("textbox", name="Имя (контактное)").press("ArrowRight")
    page.get_by_role("textbox", name="Имя (контактное)").press("ArrowRight")
    page.get_by_role("link", name="Удобства").click()
    page1.goto("https://dev2.realt.by/offers/booking-apartment/#facilities")
    page.get_by_text("Присоединиться к договору возмездного оказания рекламных услуг (посредством серв").click()
    page.get_by_role("button", name="Сохранить и продолжить").click()
    page.get_by_text("Отключить бронирования день в день", exact=True).click()
    page.get_by_role("button", name="Продолжить", exact=True).click()
    page.get_by_role("button", name="Создать настройку цены").click()
    page.get_by_role("textbox", name="Например, \"Стандартная\"").click()
    page.get_by_role("textbox", name="Например, \"Стандартная\"").fill("тестовая настройка цены")
    page.get_by_role("textbox", name="Введите").click()
    page.get_by_role("textbox", name="Введите").fill("100")
    page.get_by_role("button", name="Питомцы").click()
    page.get_by_role("row", name="+ питомец BYN").get_by_role("textbox").click()
    page.get_by_role("row", name="+ питомец BYN").get_by_role("textbox").fill("10")
    page.locator("#web-sdk-portals").get_by_role("button", name="Сохранить и продолжить").click()
    page.get_by_role("button", name="тестовая настройка цены").click()
    page.get_by_text("тестовая настройка цены").nth(1).click()
    page.get_by_text("Возможен ранний заезд").click()
    page.get_by_text("Возможен поздний выезд").click()
    page.get_by_role("textbox").click()
    page.get_by_role("textbox").fill("50")
    page.get_by_text("Предоставляется трансфер").click()
    page.get_by_role("button", name="Сохранить и продолжить").click()
    page.get_by_text("Ясно! Буду обновлять календарь или настрою синхронизацию").click()
    page.get_by_role("button", name="Продолжить", exact=True).click()
    page.get_by_role("textbox", name="Добавьте ссылку на видео").click()
    page.get_by_role("textbox", name="Добавьте ссылку на видео").press("ControlOrMeta+м")
    page.get_by_role("textbox", name="Добавьте ссылку на видео").fill("www.video.com")
    page.get_by_role("textbox", name="Добавьте ссылку на ваш объект").click()
    page.get_by_role("textbox", name="Добавьте ссылку на ваш объект").fill("www.ssilka.com")
    page.get_by_role("button", name="Отправить на проверку").click()

"""